version: '3'
services:
  neo4j:
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: none
  trkr-server:
    image: openjdk
    volumes:
      - ../build/libs:/jars
    depends_on:
      - neo4j
    links:
      - "neo4j"
    ports:
      - "8000:8000"
    environment:
      DB_TYPE: "Neo4j"
      DB_URI: "bolt://neo4j:7687"
    working_dir: "/jars/"
    command: "/bin/bash -c 'java -jar $$(ls trkr-server*.jar)'"
